_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
arch_learning_rate:
    value: 0.01
arch_weight_decay:
    value: 0.001
batch_size:
    value: 2
cutout:
    value: false
cutout_length:
    value: 16
data:
    value: ../data
device:
    value: mps
drop_path_prob:
    value: 0.3
epochs:
    value: 300
grad_clip:
    value: 5
init_channels:
    value: 16
layers:
    value: 3
learning_rate:
    value: 0.01
learning_rate_min:
    value: 0.001
model_path:
    value: saved_models
momentum:
    value: 0.9
rate:
    value:
        - 1
        - 0
report_freq:
    value: 50
save:
    value: ./log/
seed:
    value: 2
snn_step:
    value: 5
train_portion:
    value: 0.5
unrolled:
    value: false
weight_decay:
    value: 0.0003
